name: "Recommend Repo Action"
description: "Recommends Github repos based on similar pull request"
outputs:
  recommendations:
    description: "Outputs the recommendation issues list to user"
runs:
  using: "node16"
  main: "actions/index.js"
branding:
  icon: 'award'
  color: 'green'
